services:
  qbittorrent:
    container_name: qbittorrent
    image: linuxserver/qbittorrent:latest
    networks:
      - qbit-network
      - proxy-network
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.config:/config
      - /mnt/seagate-alpha/torrents:/downloads/seagate-alpha
      - /mnt/seagate-beta/torrents:/downloads/seagate-beta
networks:
  qbit-network:
    external: true
  proxy-network:
    external: true