services:
  dbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    volumes:
      - ./.config:/opt/cloudbeaver/workspace
    restart: unless-stopped
    networks:
      - db-network
      - proxy-network
  mssql-szakdoga:
    image: microsoft/mssql-server:2025-latest
    container_name: mssql-szakdoga
    env_file:
      - .db.env
    ports:
      - 3306:1433
    networks:
      - db-network
networks:
  db-network:
    external: true
  proxy-network:
    external: true