services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: proxymanager
    restart: unless-stopped
    environment:
      TZ: "Europe/Budapest"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./.data:/data
      - ./.letsencrypt:/etc/letsencrypt
networks:
  proxy-network:
    external: true