services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 7359:7359/udp
    volumes:
      - ./.config:/config
      - ./.cache:/cache
      - type: bind
        source: /mnt/seagate-alpha/torrents/media
        target: /media
      - type: bind
        source: /mnt/seagate-beta/torrents/media
        target: /media
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://tv.zsginal.hu
    networks:
      - jellyfin-network
      - proxy-network
networks:
  jellyfin-network:
    external: true
  proxy-network:
    external: true